name: oscam 
version: 'latest' 
version-script: |
  echo  $(/build/oscam/parts/oscam/build/config.sh -v)-$(/build/oscam/parts/oscam/build/config.sh -r) | sed 's/_/+/g'
summary: Open Source Conditional Access Module software 
description: |
  to be completed

#base: core18

architectures:
    - build-on: amd64
      run-on: amd64

grade: devel
confinement: devmode 

apps:
  oscam:
    command: usr/bin/oscam
    daemon: simple
    plugs:
      - network
      - network-bind
      - serial-port

parts:
  oscam:
    plugin: make
    source: http://www.streamboard.tv/svn/oscam/trunk
    source-type: svn
    override-build: | 
        ./config.sh --disable all --enable WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH READER_NAGRA READER_VIDEOGUARD CARDREADER_PHOENIX 
        make CONF_DIR=$SNAP_DATA/oscam USE_LIBUSB=1
        mkdir -p ../install/usr/bin
        rm Distribution/oscam-*.debug
        cp Distribution/oscam-* ../install/usr/bin/oscam
        
    build-packages:
      - libusb-1.0-0-dev
    stage-packages:
      - libusb-1.0-0
    stage: 
      - usr/bin/oscam
    override-prime: |
        find /
        snapcraftctl prime
